const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('usage', {
  get: () => ipcRenderer.invoke('usage:get'),
  context: () => ipcRenderer.invoke('context:get'),
  version: () => ipcRenderer.invoke('app:version'),
  onUpdate: (cb) => ipcRenderer.on('usage:update', (_e, data) => cb(data)),
  onContext: (cb) => ipcRenderer.on('context:update', (_e, data) => cb(data)),
  onError: (cb) => ipcRenderer.on('usage:error', (_e, msg) => cb(msg)),
  onSignedOut: (cb) => ipcRenderer.on('usage:signedout', () => cb()),
  refresh: () => ipcRenderer.send('widget:refresh'),
  hide: () => ipcRenderer.send('widget:hide'),
  close: () => ipcRenderer.send('widget:close'),
  accentColor: () => ipcRenderer.invoke('theme:accentColor'),
  recap: (sessionId) => ipcRenderer.invoke('session:recap', sessionId || null),
  openRecap: () => ipcRenderer.send('panel:recap'),
  sessions: () => ipcRenderer.invoke('sessions:list'),
  pinSession: (sessionId) => ipcRenderer.invoke('sessions:pin', sessionId),
  openSessions: () => ipcRenderer.send('panel:sessions'),
  openUsagePage: () => ipcRenderer.send('usage:openPage'),
  openChat: (id) => ipcRenderer.send('chat:open', id),
  scheduled: () => ipcRenderer.invoke('scheduled:list'),
  openScheduled: () => ipcRenderer.send('panel:scheduled'),
  openHelp: (section) => ipcRenderer.send('panel:help', section || 'top'),
  onGoto: (cb) => ipcRenderer.on('panel:goto', (_e, hash) => cb(hash)),
  fitHeight: (h) => ipcRenderer.send('widget:fit', h),
  autoContinue: {
    activity: () => ipcRenderer.invoke('autocontinue:activity'),
    openActivity: () => ipcRenderer.send('panel:activity'),
    get: () => ipcRenderer.invoke('autocontinue:get'),
    set: (patch) => ipcRenderer.invoke('autocontinue:set', patch),
    onChange: (cb) => ipcRenderer.on('autocontinue:update', (_e, data) => cb(data)),
  },
});
